apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: deploy-fruits-service-
spec:
  entrypoint: ci-example
  templates:
  - name: ci-example
    steps:
      - - name: run-tests
          template: test
  - name: test
    container:
      image: 'golang:latest'
      command: [sh,-c]
      args: ["cd /go/src/github.com/viggin543/golang_service;go mod download; go test ./..."]
      env:
      - name: DB_HOST
        value: "127.0.0.1"
      sidecars:
        - name: mysql:5.7
          image: mysql:5.7
          env:
          - name: MYSQL_USER
            value: root
          - name: root
            value: password
          - name: MYSQL_DATABASE
            value: frutas
    inputs:
      artifacts:
        - git: { repo: 'https://github.com/viggin543/golang_service.git', revision: '6631bbc'}
          name: code
          path: /go/src/github.com/viggin543/golang_service

